name:                gameofwords
version:             0.1.0.0
github:              "avelx/gameofwords"
license:             BSD3
author:              "Pavel Oliynyk (based on the Udemy Haskell course)"
maintainer:          "pavel.oliynyk@gmail.com"
copyright:           "BSD"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Game

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/avelx/gameofwords#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  gameofwords-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gameofwords

tests:
  gameofwords-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gameofwords
